### PR TITLE
🔧  Fixing the provisioned test server that will not crash

### LINKED ISSUE #31: Fix: Make provisioned test server not crash
The way we launched the Django dev server in the provision script had
caused it to crash every time we change the code.
 With the new command, it reloads the code as it needs to.
- [ ] Fix the runserver command in setup.sh file

### PR DESCRIPTION
**Pull request by ErezCohenn**
The way we launched the Django dev server in the provision script had
caused it to crash every time we change the code.
With the new command that updated on setup.sh file, it reloads the web application as we will edit the code

Close #31 

Signed-off-by: Erez Cohen <erez6356458@gmail.com>

### CODE REVIEW

**Review by tamirmatok — APPROVED** [review]
Good job @ErezCohenn

File: setup.sh [hunk 1]
```diff
@@ -10,6 +10,7 @@ cd /vagrant
 # Install dependencies with Pipenv
 pipenv sync --dev
 
-# run our app. Nohup and "&" are used to let the setup script finish
-# while our app stays up. The app logs will be collected in nohup.out
-nohup pipenv run python manage.py runserver 0.0.0.0:8000 &
+# run our app. setsit, the parentheses and "&" are used to perform a "double
+# fork" so that out app stays up after the setup script finishes.
+# The app logs are redirected to the `runserver.log` file.
+(setsid pipenv run python manage.py runserver 0.0.0.0:8000 > runserver.log 2>&1 &)
```
Comment (Omeramsc) [inline setup.sh:16]: what made the app crash with what you used before? I never saw it happen.

Comment (ErezCohenn) [reply setup.sh:16]: Always when we changed the code of the project the server was failed and we had to run the command:
 `vagrant provision`. 
Now it should be resolved as Barak Korren mentioned in the slack [here](https://redhat-beyond.slack.com/archives/C031MUZG0LE/p1647795038129999)

Comment (Omeramsc) [reply setup.sh:16]: Right, thanks. :)
